### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by lieuzhenghong**
Hi Jordan, 

Thanks for building this. It's very nifty!

**Don't merge this PR** (it might break prod if `UserModel.exists` is false). But keep reading:

Are you open to contributors? I thought it might be a good idea to write some tests for the `extract_pdf` function so that it could be refactored to implement the various new features (#6, #7, #9). But in order to do that, I've had to break prod, unfortunately. The issue I've had is with lines 25 and 26 of `users.py`: is it possible to put them inside the class initialisation, or tuck it in the `main` function inside `lambda.py`? That would allow the tests I've written to run without errors.

Thanks for your time!
ZH

### CODE REVIEW

**Comment by j6k4m8** [comment]
Wow @lieuzhenghong this looks super awesome! I'd love to merge this in :) Let me take a closer look later today (I'm in GMT-5)!

**Comment by lieuzhenghong** [comment]
Hi @j6k4m8 , gentle ping to ask if you'd be able to look at this today :)

**Comment by j6k4m8** [comment]
Sorry for the lag here — yes, this looks wonderful! 

My only remaining concern before merging is about taking out the User table provisioning two-liner. But probably this should live in [`provision.py`](https://github.com/j6k4m8/remailable/blob/master/provision.py) anyway! 

If you're ready to merge this now, I say let's go for it and then I'll make that change in a bit :) Thanks for your patience, had a wild day yesterday!

**Comment by lieuzhenghong** [comment]
No worries! The only person who can merge the PR is you, so anytime you're ready :)

**Pull request merged**
